# Generated by Django 3.1.1 on 2020-11-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='drawing_app.profile'),
            preserve_default=False,
        ),
    ]
