# Generated by Django 3.1.5 on 2021-01-29 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawing_app', '0002_remove_profile_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
