# Generated by Django 3.1.5 on 2021-04-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0002_post_interaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='interaction',
            new_name='current_interaction',
        ),
        migrations.AddField(
            model_name='post',
            name='last_interaction',
            field=models.IntegerField(default=0),
        ),
    ]
