# Generated by Django 3.1.5 on 2021-01-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0003_auto_20201111_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='canvas',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='drawing_app.canvas'),
        ),
    ]
