# Generated by Django 3.1.5 on 2021-01-29 19:47

from django.db import migrations, models
import drawing_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0003_auto_20210129_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, upload_to=drawing_app.models.image_upload_path),
        ),
    ]
