# Generated by Django 3.1.5 on 2021-04-01 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0003_auto_20210401_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interaction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='last_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
