# Generated by Django 3.1.5 on 2021-01-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0004_auto_20210129_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
