# Generated by Django 3.1.5 on 2021-01-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0004_auto_20210108_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomBackground',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
