# Generated by Django 3.1.5 on 2021-04-07 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0007_auto_20210407_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 14, 54, 6, 587476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 14, 54, 6, 587476, tzinfo=utc)),
        ),
    ]
