# Generated by Django 3.1.5 on 2021-04-07 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0008_auto_20210407_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commment',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 15, 49, 24, 689455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 15, 49, 24, 689455, tzinfo=utc)),
        ),
    ]
