# Generated by Django 3.1.5 on 2021-04-07 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0009_auto_20210407_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commment',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='last_update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 15, 51, 22, 805504, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 15, 51, 22, 805504, tzinfo=utc)),
        ),
    ]
