# Generated by Django 3.1.5 on 2021-04-07 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0011_auto_20210407_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
