# Generated by Django 3.1.5 on 2021-04-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0012_auto_20210407_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvas',
            name='canvas_name',
        ),
    ]
