# Generated by Django 3.1.5 on 2021-04-13 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0013_remove_canvas_canvas_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing_app.room'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('canvas', 'index')},
        ),
        migrations.DeleteModel(
            name='Canvas',
        ),
    ]
