# Generated by Django 3.1.5 on 2021-04-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0014_auto_20210413_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='image',
        ),
    ]
