# Generated by Django 3.1.5 on 2021-04-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_app', '0015_remove_layer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
